export const REQUEST_FETCH_FOSSIL = 'FOSSIL/REQUEST_FETCH_FOSSIL';
export const REQUEST_FETCH_FOSSIL_SUCCESS = 'FOSSIL/REQUEST_FETCH_FOSSIL_SUCCESS';
export const REQUEST_FETCH_FOSSIL_FAIL = 'FOSSIL/REQUEST_FETCH_FOSSIL_FAIL';

export const REQUEST_ADD_FRONT = 'FOSSIL/REQUEST_ADD_FRONT';
export const REQUEST_EDIT_FORM = 'FOSSIL/REQUEST_EDIT_FORM';
export const REQUEST_EDIT_FRONT = 'FOSSIL/REQUEST_EDIT_FRONT';
export const REQUEST_CANCEL_EDIT = 'FOSSIL/REQUEST_CANCEL_EDIT';
export const REQUEST_DELETE_FRONT = 'FOSSIL/REQUEST_DELETE_FRONT';

export const REQUEST_FILTER_DATE_FRONT = 'FOSSIL/REQUEST_FILTER_DATE_FRONT';
export const REQUEST_CANCEL_FILTER_DATE = 'FOSSIL/REQUEST_CANCEL_FILTER_DATE';

export const REQUEST_SORT_DATE_FRONT = 'FOSSIL/REQUEST_SORT_DATE_FRONT';
export const REQUEST_SORT_DESC_DATE_FRONT = 'FOSSIL/REQUEST_SORT_DESC_DATE_FRONT';
export const REQUEST_CANCEL_SORT_DATE = 'FOSSIL/REQUEST_CANCEL_SORT_DATE';

export const REQUEST_SEARCH = 'FOSSIL/REQUEST_SEARCH';
export const REQUEST_SEARCH_SUCCESS = 'FOSSIL/REQUEST_SEARCH_SUCCESS';
export const REQUEST_SEARCH_FAIL = 'FOSSIL/REQUEST_SEARCH_FAIL';